/* Generated By:JavaCC: Do not edit this line. DDLParserTreeConstants.java Version 5.0 */
package org.eclipse.persistence.tools.oracleddl.parser;

@SuppressWarnings("all")
public interface DDLParserTreeConstants
{
  public int JJTPARSEPLSQLPACKAGE = 0;
  public int JJTPARSETOPLEVELPROCEDURE = 1;
  public int JJTPARSETOPLEVELFUNCTION = 2;
  public int JJTPARSETABLE = 3;
  public int JJTPARSETYPE = 4;
  public int JJTVOID = 5;
  public int JJTCOLUMNTYPESPEC = 6;
  public int JJTVARIABLEDECLARATION = 7;
  public int JJTDATATYPE = 8;
  public int JJTTYPESPEC = 9;
  public int JJTFIELDDECLARATION = 10;
  public int JJTFUNCTIONRETURNSPEC = 11;
  public int JJTARGUMENT = 12;
  public int JJTARGUMENTDEFAULTASSIGNMENT = 13;


  public String[] jjtNodeName = {
    "parsePLSQLPackage",
    "parseTopLevelProcedure",
    "parseTopLevelFunction",
    "parseTable",
    "parseType",
    "void",
    "columnTypeSpec",
    "variableDeclaration",
    "datatype",
    "typeSpec",
    "fieldDeclaration",
    "functionReturnSpec",
    "argument",
    "argumentDefaultAssignment",
  };
}
/* JavaCC - OriginalChecksum=4a0f489189e4c3ead4b8cf5fc0c660e0 (do not edit this line) */
