/* Generated By:JavaCC: Do not edit this line. DDLParserTreeConstants.java Version 5.0 */
package org.eclipse.persistence.tools.oracleddl.parser;

@SuppressWarnings("all")
public interface DDLParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=ff721d13e20dfc97bde0c0e42bb97d94 (do not edit this line) */
