/* Generated By:JavaCC: Do not edit this line. DDLParserVisitor.java Version 5.0 */
package org.eclipse.persistence.tools.oracleddl.parser;

@SuppressWarnings("all")
public interface DDLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=0a5f7f17a0ed392fca069d04f2c11cb5 (do not edit this line) */
