/* Generated By:JavaCC: Do not edit this line. DDLParserTreeConstants.java Version 5.0 */
package org.eclipse.persistence.tools.oracleddl.parser;

@SuppressWarnings("all")
public interface DDLParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=46585a43045182b363c9163878500a1a (do not edit this line) */
