/* Generated By:JavaCC: Do not edit this line. DDLParserVisitor.java Version 5.0 */
package org.eclipse.persistence.tools.oracleddl.parser;

@SuppressWarnings("all")
public interface DDLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=1ef80f9e87a51db5c74f170fc3e9781d (do not edit this line) */
