/* Generated By:JJTree&JavaCC: Do not edit this line. DDLParserConstants.java */
/*******************************************************************************
 * Copyright (c) 2011 Oracle. All rights reserved.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 and Eclipse Distribution License v. 1.0
 * which accompanies this distribution.
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *     Mike Norman - June 10 2011, created DDL parser package
 ******************************************************************************/
package org.eclipse.persistence.tools.oracleddl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface DDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_LINE = 6;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 7;
  /** RegularExpression Id. */
  int O_ASSIGN = 8;
  /** RegularExpression Id. */
  int O_ASTERISK = 9;
  /** RegularExpression Id. */
  int O_ATSIGN = 10;
  /** RegularExpression Id. */
  int O_CLOSEPAREN = 11;
  /** RegularExpression Id. */
  int O_CONCAT = 12;
  /** RegularExpression Id. */
  int O_COLON = 13;
  /** RegularExpression Id. */
  int O_COMMA = 14;
  /** RegularExpression Id. */
  int O_DOT = 15;
  /** RegularExpression Id. */
  int O_DOUBLEDOT = 16;
  /** RegularExpression Id. */
  int O_DOLLAR = 17;
  /** RegularExpression Id. */
  int O_PERCENT = 18;
  /** RegularExpression Id. */
  int O_EQUAL = 19;
  /** RegularExpression Id. */
  int O_GREATER = 20;
  /** RegularExpression Id. */
  int O_GREATEREQUAL = 21;
  /** RegularExpression Id. */
  int O_JOINPLUS = 22;
  /** RegularExpression Id. */
  int O_LESS = 23;
  /** RegularExpression Id. */
  int O_LESSEQUAL = 24;
  /** RegularExpression Id. */
  int O_MINUS = 25;
  /** RegularExpression Id. */
  int O_NOTEQUAL2 = 26;
  /** RegularExpression Id. */
  int O_NOTEQUAL = 27;
  /** RegularExpression Id. */
  int O_OPENPAREN = 28;
  /** RegularExpression Id. */
  int O_PLUS = 29;
  /** RegularExpression Id. */
  int O_POUND = 30;
  /** RegularExpression Id. */
  int O_QUESTIONMARK = 31;
  /** RegularExpression Id. */
  int O_SEMICOLON = 32;
  /** RegularExpression Id. */
  int O_SLASH = 33;
  /** RegularExpression Id. */
  int O_TILDE = 34;
  /** RegularExpression Id. */
  int S_NUMBER = 35;
  /** RegularExpression Id. */
  int FLOAT = 36;
  /** RegularExpression Id. */
  int INTEGER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int K_A = 39;
  /** RegularExpression Id. */
  int K_ADD = 40;
  /** RegularExpression Id. */
  int K_ALTER = 41;
  /** RegularExpression Id. */
  int K_ARRAY = 42;
  /** RegularExpression Id. */
  int K_AS = 43;
  /** RegularExpression Id. */
  int K_AUTHID = 44;
  /** RegularExpression Id. */
  int K_AUTOMATIC = 45;
  /** RegularExpression Id. */
  int K_AUTONOMOUS_TRANSACTION = 46;
  /** RegularExpression Id. */
  int K_BEGIN = 47;
  /** RegularExpression Id. */
  int K_BFILE = 48;
  /** RegularExpression Id. */
  int K_BINARY_DOUBLE = 49;
  /** RegularExpression Id. */
  int K_BINARY_FLOAT = 50;
  /** RegularExpression Id. */
  int K_BINARY_INTEGER = 51;
  /** RegularExpression Id. */
  int K_BLOB = 52;
  /** RegularExpression Id. */
  int K_BODY = 53;
  /** RegularExpression Id. */
  int K_BOOLEAN = 54;
  /** RegularExpression Id. */
  int K_BUILTIN = 55;
  /** RegularExpression Id. */
  int K_BULK = 56;
  /** RegularExpression Id. */
  int K_BY = 57;
  /** RegularExpression Id. */
  int K_BYTE = 58;
  /** RegularExpression Id. */
  int K_CHAR = 59;
  /** RegularExpression Id. */
  int K_CHARACTER = 60;
  /** RegularExpression Id. */
  int K_CHARSET = 61;
  /** RegularExpression Id. */
  int K_CHECK = 62;
  /** RegularExpression Id. */
  int K_CLOB = 63;
  /** RegularExpression Id. */
  int K_CLOSE = 64;
  /** RegularExpression Id. */
  int K_COLLECT = 65;
  /** RegularExpression Id. */
  int K_COMMIT = 66;
  /** RegularExpression Id. */
  int K_CONSTANT = 67;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 68;
  /** RegularExpression Id. */
  int K_COUNT = 69;
  /** RegularExpression Id. */
  int K_CREATE = 70;
  /** RegularExpression Id. */
  int K_CROSS = 71;
  /** RegularExpression Id. */
  int K_CUBE = 72;
  /** RegularExpression Id. */
  int K_CURRENT_OF = 73;
  /** RegularExpression Id. */
  int K_CURRENT_USER = 74;
  /** RegularExpression Id. */
  int K_CURSOR = 75;
  /** RegularExpression Id. */
  int K_DATE = 76;
  /** RegularExpression Id. */
  int K_DAY = 77;
  /** RegularExpression Id. */
  int K_DBTIMEZONE = 78;
  /** RegularExpression Id. */
  int K_DEC = 79;
  /** RegularExpression Id. */
  int K_DECIMAL = 80;
  /** RegularExpression Id. */
  int K_DECREMENT = 81;
  /** RegularExpression Id. */
  int K_DEFAULT = 82;
  /** RegularExpression Id. */
  int K_DEFINER = 83;
  /** RegularExpression Id. */
  int K_DELETE = 84;
  /** RegularExpression Id. */
  int K_DETERMINISTIC = 85;
  /** RegularExpression Id. */
  int K_DIMENSION = 86;
  /** RegularExpression Id. */
  int K_DOUBLE = 87;
  /** RegularExpression Id. */
  int K_ELSIF = 88;
  /** RegularExpression Id. */
  int K_EMPTY = 89;
  /** RegularExpression Id. */
  int K_ENABLE = 90;
  /** RegularExpression Id. */
  int K_END = 91;
  /** RegularExpression Id. */
  int K_EQUALS_PATH = 92;
  /** RegularExpression Id. */
  int K_ESCAPE = 93;
  /** RegularExpression Id. */
  int K_EXCEPTION = 94;
  /** RegularExpression Id. */
  int K_EXCEPTION_INIT = 95;
  /** RegularExpression Id. */
  int K_EXIT = 96;
  /** RegularExpression Id. */
  int K_FALSE = 97;
  /** RegularExpression Id. */
  int K_FINAL = 98;
  /** RegularExpression Id. */
  int K_FIPSFLAG = 99;
  /** RegularExpression Id. */
  int K_FIRST = 100;
  /** RegularExpression Id. */
  int K_FLOAT = 101;
  /** RegularExpression Id. */
  int K_FORCE = 102;
  /** RegularExpression Id. */
  int K_FULL = 103;
  /** RegularExpression Id. */
  int K_FUNCTION = 104;
  /** RegularExpression Id. */
  int K_GLOBAL = 105;
  /** RegularExpression Id. */
  int K_GROUPING = 106;
  /** RegularExpression Id. */
  int K_IGNORE = 107;
  /** RegularExpression Id. */
  int K_IN = 108;
  /** RegularExpression Id. */
  int K_INCREMENT = 109;
  /** RegularExpression Id. */
  int K_INDEX = 110;
  /** RegularExpression Id. */
  int K_INFINITE = 111;
  /** RegularExpression Id. */
  int K_INLINE = 112;
  /** RegularExpression Id. */
  int K_INNER = 113;
  /** RegularExpression Id. */
  int K_INSTANTIABLE = 114;
  /** RegularExpression Id. */
  int K_INT = 115;
  /** RegularExpression Id. */
  int K_INTEGER = 116;
  /** RegularExpression Id. */
  int K_INTERFACE = 117;
  /** RegularExpression Id. */
  int K_INTERVAL = 118;
  /** RegularExpression Id. */
  int K_IS = 119;
  /** RegularExpression Id. */
  int K_ITERATE = 120;
  /** RegularExpression Id. */
  int K_JOIN = 121;
  /** RegularExpression Id. */
  int K_KEY = 122;
  /** RegularExpression Id. */
  int K_KEEP = 123;
  /** RegularExpression Id. */
  int K_LAST = 124;
  /** RegularExpression Id. */
  int K_LEFT = 125;
  /** RegularExpression Id. */
  int K_LIKE2 = 126;
  /** RegularExpression Id. */
  int K_LIKE4 = 127;
  /** RegularExpression Id. */
  int K_LIKEC = 128;
  /** RegularExpression Id. */
  int K_LOCAL = 129;
  /** RegularExpression Id. */
  int K_LONG = 130;
  /** RegularExpression Id. */
  int K_LOOP = 131;
  /** RegularExpression Id. */
  int K_MAIN = 132;
  /** RegularExpression Id. */
  int K_MEASURES = 133;
  /** RegularExpression Id. */
  int K_MEMBER = 134;
  /** RegularExpression Id. */
  int K_MLSLABEL = 135;
  /** RegularExpression Id. */
  int K_MODEL = 136;
  /** RegularExpression Id. */
  int K_MONTH = 137;
  /** RegularExpression Id. */
  int K_NAN = 138;
  /** RegularExpression Id. */
  int K_NATIONAL = 139;
  /** RegularExpression Id. */
  int K_NATURAL = 140;
  /** RegularExpression Id. */
  int K_NAV = 141;
  /** RegularExpression Id. */
  int K_NCHAR = 142;
  /** RegularExpression Id. */
  int K_NCLOB = 143;
  /** RegularExpression Id. */
  int K_NEW_NAMES = 144;
  /** RegularExpression Id. */
  int K_NO = 145;
  /** RegularExpression Id. */
  int K_NOCOMPRESS = 146;
  /** RegularExpression Id. */
  int K_NOCOPY = 147;
  /** RegularExpression Id. */
  int K_NOCYCLE = 148;
  /** RegularExpression Id. */
  int K_NOT = 149;
  /** RegularExpression Id. */
  int K_NULL = 150;
  /** RegularExpression Id. */
  int K_NULLS = 151;
  /** RegularExpression Id. */
  int K_NUMBER = 152;
  /** RegularExpression Id. */
  int K_NUMERIC = 153;
  /** RegularExpression Id. */
  int K_NVARCHAR2 = 154;
  /** RegularExpression Id. */
  int K_NVARCHAR = 155;
  /** RegularExpression Id. */
  int K_OBJECT = 156;
  /** RegularExpression Id. */
  int K_OF = 157;
  /** RegularExpression Id. */
  int K_OID = 158;
  /** RegularExpression Id. */
  int K_ON = 159;
  /** RegularExpression Id. */
  int K_ONLY = 160;
  /** RegularExpression Id. */
  int K_OPEN = 161;
  /** RegularExpression Id. */
  int K_OR = 162;
  /** RegularExpression Id. */
  int K_ORGANIZATION = 163;
  /** RegularExpression Id. */
  int K_OUT = 164;
  /** RegularExpression Id. */
  int K_OUTER = 165;
  /** RegularExpression Id. */
  int K_OVERFLOW = 166;
  /** RegularExpression Id. */
  int K_PACKAGE = 167;
  /** RegularExpression Id. */
  int K_PARALLEL_ENABLE = 168;
  /** RegularExpression Id. */
  int K_PARTITION = 169;
  /** RegularExpression Id. */
  int K_PIPELINED = 170;
  /** RegularExpression Id. */
  int K_PLS_INTEGER = 171;
  /** RegularExpression Id. */
  int K_POSITIVE = 172;
  /** RegularExpression Id. */
  int K_PRAGMA = 173;
  /** RegularExpression Id. */
  int K_PRECISION = 174;
  /** RegularExpression Id. */
  int K_PRESENT = 175;
  /** RegularExpression Id. */
  int K_PRESERVE = 176;
  /** RegularExpression Id. */
  int K_PRIMARY = 177;
  /** RegularExpression Id. */
  int K_PROCEDURE = 178;
  /** RegularExpression Id. */
  int K_RAISE = 179;
  /** RegularExpression Id. */
  int K_RANGE = 180;
  /** RegularExpression Id. */
  int K_RAW = 181;
  /** RegularExpression Id. */
  int K_READ = 182;
  /** RegularExpression Id. */
  int K_REAL = 183;
  /** RegularExpression Id. */
  int K_RECORD = 184;
  /** RegularExpression Id. */
  int K_REF = 185;
  /** RegularExpression Id. */
  int K_REFERENCE = 186;
  /** RegularExpression Id. */
  int K_REGEXP_LIKE = 187;
  /** RegularExpression Id. */
  int K_REPLACE = 188;
  /** RegularExpression Id. */
  int K_RESTRICT_REFERENCES = 189;
  /** RegularExpression Id. */
  int K_RESULT_CACHE = 190;
  /** RegularExpression Id. */
  int K_RETURN = 191;
  /** RegularExpression Id. */
  int K_RETURNING = 192;
  /** RegularExpression Id. */
  int K_REVERSE = 193;
  /** RegularExpression Id. */
  int K_RIGHT = 194;
  /** RegularExpression Id. */
  int K_RNDS = 195;
  /** RegularExpression Id. */
  int K_RNPS = 196;
  /** RegularExpression Id. */
  int K_ROLLBACK = 197;
  /** RegularExpression Id. */
  int K_ROLLUP = 198;
  /** RegularExpression Id. */
  int K_ROWID = 199;
  /** RegularExpression Id. */
  int K_ROWS = 200;
  /** RegularExpression Id. */
  int K_ROWTYPE = 201;
  /** RegularExpression Id. */
  int K_RULES = 202;
  /** RegularExpression Id. */
  int K_SECOND = 203;
  /** RegularExpression Id. */
  int K_SEQUENTIAL = 204;
  /** RegularExpression Id. */
  int K_SERIALLY_REUSABLE = 205;
  /** RegularExpression Id. */
  int K_SESSIONTIMEZONE = 206;
  /** RegularExpression Id. */
  int K_SET = 207;
  /** RegularExpression Id. */
  int K_SETS = 208;
  /** RegularExpression Id. */
  int K_SIBLINGS = 209;
  /** RegularExpression Id. */
  int K_SIGNTYPE = 210;
  /** RegularExpression Id. */
  int K_SINGLE = 211;
  /** RegularExpression Id. */
  int K_SIMPLE_INTEGER = 212;
  /** RegularExpression Id. */
  int K_SIMPLE_DOUBLE = 213;
  /** RegularExpression Id. */
  int K_SIMPLE_FLOAT = 214;
  /** RegularExpression Id. */
  int K_SMALLINT = 215;
  /** RegularExpression Id. */
  int K_SOME = 216;
  /** RegularExpression Id. */
  int K_STRING = 217;
  /** RegularExpression Id. */
  int K_SUBMUlookISET = 218;
  /** RegularExpression Id. */
  int K_SUBTYPE = 219;
  /** RegularExpression Id. */
  int K_SYS_REFCURSOR = 220;
  /** RegularExpression Id. */
  int K_TABLE = 221;
  /** RegularExpression Id. */
  int K_TEMPORARY = 222;
  /** RegularExpression Id. */
  int K_THE = 223;
  /** RegularExpression Id. */
  int K_TIME = 224;
  /** RegularExpression Id. */
  int K_TIMESTAMP = 225;
  /** RegularExpression Id. */
  int K_TO = 226;
  /** RegularExpression Id. */
  int K_TRANSACTION = 227;
  /** RegularExpression Id. */
  int K_TRUE = 228;
  /** RegularExpression Id. */
  int K_TRUST = 229;
  /** RegularExpression Id. */
  int K_TYPE = 230;
  /** RegularExpression Id. */
  int K_TYPE2 = 231;
  /** RegularExpression Id. */
  int K_UNDER_PATH = 232;
  /** RegularExpression Id. */
  int K_UNIQUE = 233;
  /** RegularExpression Id. */
  int K_UNTIL = 234;
  /** RegularExpression Id. */
  int K_UPDATED = 235;
  /** RegularExpression Id. */
  int K_UPSERT = 236;
  /** RegularExpression Id. */
  int K_UROWID = 237;
  /** RegularExpression Id. */
  int K_USING = 238;
  /** RegularExpression Id. */
  int K_VARCHAR2 = 239;
  /** RegularExpression Id. */
  int K_VARCHAR = 240;
  /** RegularExpression Id. */
  int K_VARRAY = 241;
  /** RegularExpression Id. */
  int K_VARYING = 242;
  /** RegularExpression Id. */
  int K_WITH = 243;
  /** RegularExpression Id. */
  int K_WHILE = 244;
  /** RegularExpression Id. */
  int K_WNDS = 245;
  /** RegularExpression Id. */
  int K_WNPS = 246;
  /** RegularExpression Id. */
  int K_WORK = 247;
  /** RegularExpression Id. */
  int K_YEAR = 248;
  /** RegularExpression Id. */
  int K_YES = 249;
  /** RegularExpression Id. */
  int K_ZONE = 250;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 251;
  /** RegularExpression Id. */
  int LETTER = 252;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 253;
  /** RegularExpression Id. */
  int S_BIND = 254;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 255;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 256;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT_LINE>",
    "<COMMENT_BLOCK>",
    "\":=\"",
    "\"*\"",
    "\"@\"",
    "\")\"",
    "\"||\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"..\"",
    "\"$\"",
    "\"%\"",
    "\"=\"",
    "\">\"",
    "\">=\"",
    "\"(+)\"",
    "\"<\"",
    "\"<=\"",
    "\"-\"",
    "\"<>\"",
    "\"!=\"",
    "\"(\"",
    "\"+\"",
    "\"#\"",
    "\"?\"",
    "\";\"",
    "\"/\"",
    "\"~\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "\"A\"",
    "\"ADD\"",
    "\"ALTER\"",
    "\"ARRAY\"",
    "\"AS\"",
    "\"AUTHID\"",
    "\"AUTOMATIC\"",
    "\"AUTONOMOUS_TRANSACTION\"",
    "\"BEGIN\"",
    "\"BFILE\"",
    "\"BINARY_DOUBLE\"",
    "\"BINARY_FLOAT\"",
    "\"BINARY_INTEGER\"",
    "\"BLOB\"",
    "\"BODY\"",
    "\"BOOLEAN\"",
    "\"BUILTIN\"",
    "\"BULK\"",
    "\"BY\"",
    "\"BYTE\"",
    "\"CHAR\"",
    "\"CHARACTER\"",
    "\"%CHARSET\"",
    "\"CHECK\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COLLECT\"",
    "\"COMMIT\"",
    "\"CONSTANT\"",
    "\"CONSTRAINT\"",
    "\"COUNT\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CURRENT_OF\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"DATE\"",
    "\"DAY\"",
    "\"DBTIMEZONE\"",
    "\"DEC\"",
    "\"DECIMAL\"",
    "\"DECREMENT\"",
    "\"DEFAULT\"",
    "\"DEFINER\"",
    "\"DELETE\"",
    "\"DETERMINISTIC\"",
    "\"DIMENSION\"",
    "\"DOUBLE\"",
    "\"ELSIF\"",
    "\"EMPTY\"",
    "\"ENABLE\"",
    "\"END\"",
    "\"EQUALS_PATH\"",
    "\"ESCAPE\"",
    "\"EXCEPTION\"",
    "\"EXCEPTION_INIT\"",
    "\"EXIT\"",
    "\"FALSE\"",
    "\"FINAL\"",
    "\"FIPSFLAG\"",
    "\"FIRST\"",
    "\"FLOAT\"",
    "\"FORCE\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"GLOBAL\"",
    "\"GROUPING\"",
    "\"IGNORE\"",
    "\"IN\"",
    "\"INCREMENT\"",
    "\"INDEX\"",
    "\"INFINITE\"",
    "\"INLINE\"",
    "\"INNER\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERFACE\"",
    "\"INTERVAL\"",
    "\"IS\"",
    "\"ITERATE\"",
    "\"JOIN\"",
    "\"KEY\"",
    "\"KEEP\"",
    "\"LAST\"",
    "\"LEFT\"",
    "\"LIKE2\"",
    "\"LIKE4\"",
    "\"LIKEC\"",
    "\"LOCAL\"",
    "\"LONG\"",
    "\"LOOP\"",
    "\"MAIN\"",
    "\"MEASURES\"",
    "\"MEMBER\"",
    "\"MLSLABEL\"",
    "\"MODEL\"",
    "\"MONTH\"",
    "\"NAN\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NAV\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NEW_NAMES\"",
    "\"\\\'NO\\\'\"",
    "\"NOCOMPRESS\"",
    "\"NOCOPY\"",
    "\"NOCYCLE\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"NVARCHAR2\"",
    "\"NVARCHAR\"",
    "\"OBJECT\"",
    "\"OF\"",
    "\"OID\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OR\"",
    "\"ORGANIZATION\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OVERFLOW\"",
    "\"PACKAGE\"",
    "\"PARALLEL_ENABLE\"",
    "\"PARTITION\"",
    "\"PIPELINED\"",
    "\"PLS_INTEGER\"",
    "\"POSITIVE\"",
    "\"PRAGMA\"",
    "\"PRECISION\"",
    "\"PRESENT\"",
    "\"PRESERVE\"",
    "\"PRIMARY\"",
    "\"PROCEDURE\"",
    "\"RAISE\"",
    "\"RANGE\"",
    "\"RAW\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RECORD\"",
    "\"REF\"",
    "\"REFERENCE\"",
    "\"REGEXP_LIKE\"",
    "\"REPLACE\"",
    "\"RESTRICT_REFERENCES\"",
    "\"RESULT_CACHE\"",
    "\"RETURN\"",
    "\"RETURNING\"",
    "\"REVERSE\"",
    "\"RIGHT\"",
    "\"RNDS\"",
    "\"RNPS\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROWID\"",
    "\"ROWS\"",
    "\"%ROWTYPE\"",
    "\"RULES\"",
    "\"SECOND\"",
    "\"SEQUENTIAL\"",
    "\"SERIALLY_REUSABLE\"",
    "\"SESSIONTIMEZONE\"",
    "\"SET\"",
    "\"SETS\"",
    "\"SIBLINGS\"",
    "\"SIGNTYPE\"",
    "\"SINGLE\"",
    "\"SIMPLE_INTEGER\"",
    "\"SIMPLE_DOUBLE\"",
    "\"SIMPLE_FLOAT\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"STRING\"",
    "\"SUBMUlookISET\"",
    "\"SUBTYPE\"",
    "\"SYS_REFCURSOR\"",
    "\"TABLE\"",
    "\"TEMPORARY\"",
    "\"THE\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TO\"",
    "\"TRANSACTION\"",
    "\"TRUE\"",
    "\"TRUST\"",
    "\"TYPE\"",
    "\"%TYPE\"",
    "\"UNDER_PATH\"",
    "\"UNIQUE\"",
    "\"UNTIL\"",
    "\"UPDATED\"",
    "\"UPSERT\"",
    "\"UROWID\"",
    "\"USING\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"VARRAY\"",
    "\"VARYING\"",
    "\"WITH\"",
    "\"WHILE\"",
    "\"WNDS\"",
    "\"WNPS\"",
    "\"WORK\"",
    "\"YEAR\"",
    "\"\\\'YES\\\'\"",
    "\"ZONE\"",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
  };

}
