/* Generated By:JavaCC: Do not edit this line. PLSQLParserVisitor.java Version 5.0 */
package org.eclipse.persistence.tools.dbws.plsqlparser;

public interface PLSQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=d338f6ce6ba766c52a7fa8971dd869da (do not edit this line) */
