/* Generated By:JavaCC: Do not edit this line. PLSQLParserTreeConstants.java Version 5.0 */
package org.eclipse.persistence.tools.dbws.plsqlparser;

public interface PLSQLParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTPARSEPLSQLPACKAGE = 1;
  public int JJTENDPACKAGESPEC = 2;
  public int JJTPACKAGESPEC = 3;
  public int JJTVARIABLEDECLARATION = 4;
  public int JJTDATATYPE = 5;
  public int JJTTYPESPEC = 6;
  public int JJTCOLUMNSPEC = 7;
  public int JJTTABLESPEC = 8;
  public int JJTTYPEDECLARATION = 9;
  public int JJTRECORDDECLARATION = 10;
  public int JJTFIELDDECLARATION = 11;
  public int JJTFIELDTYPE = 12;
  public int JJTSUBTYPEDECLARATION = 13;
  public int JJTPLSQLTABLEDECLARATION = 14;
  public int JJTVARRAYDECLARATION = 15;
  public int JJTREFCURSORDECLARATION = 16;
  public int JJTCURSORDECLARATION = 17;
  public int JJTPROCEDURESPEC = 18;
  public int JJTARGUMENTLIST = 19;
  public int JJTFUNCTIONSPEC = 20;
  public int JJTARGUMENT = 21;
  public int JJTEXCEPTIONDECLARATION = 22;
  public int JJTPRAGMADECLARATION = 23;
  public int JJTSKIPTOSEMICOLON = 24;
  public int JJTSKIPTONEXTARG = 25;


  public String[] jjtNodeName = {
    "void",
    "parsePLSQLPackage",
    "endPackageSpec",
    "packageSpec",
    "variableDeclaration",
    "datatype",
    "typeSpec",
    "columnSpec",
    "tableSpec",
    "typeDeclaration",
    "recordDeclaration",
    "fieldDeclaration",
    "fieldType",
    "subtypeDeclaration",
    "plsqlTableDeclaration",
    "varrayDeclaration",
    "refCursorDeclaration",
    "cursorDeclaration",
    "procedureSpec",
    "argumentList",
    "functionSpec",
    "argument",
    "exceptionDeclaration",
    "pragmaDeclaration",
    "skipToSemicolon",
    "skipToNextArg",
  };
}
/* JavaCC - OriginalChecksum=a1612ace0e7aacdd28f9554a4bcfc971 (do not edit this line) */
