/* Generated By:JavaCC: Do not edit this line. PLSQLParserTreeConstants.java Version 5.0 */
package org.eclipse.persistence.tools.dbws.plsqlparser;

public interface PLSQLParserTreeConstants
{
  public int JJTORACLEOBJECTNAME = 0;
  public int JJTPARSEPLSQLPACKAGE = 1;
  public int JJTTYPEDECLARATION = 2;
  public int JJTCURSORDECLARATION = 3;
  public int JJTFUNCTIONDECLARATION = 4;
  public int JJTPROCEDUREDECLARATION = 5;
  public int JJTPRAGMADECLARATION = 6;
  public int JJTTYPEDECLARATIONBODY = 7;
  public int JJTFUNCTIONDECLARATIONBODY = 8;
  public int JJTPROCEDUREDECLARATIONBODY = 9;


  public String[] jjtNodeName = {
    "OracleObjectName",
    "parsePLSQLPackage",
    "typeDeclaration",
    "cursorDeclaration",
    "functionDeclaration",
    "procedureDeclaration",
    "pragmaDeclaration",
    "typeDeclarationBody",
    "functionDeclarationBody",
    "procedureDeclarationBody",
  };
}
/* JavaCC - OriginalChecksum=5037cef57a114955a6eb70a8bf7bc9c8 (do not edit this line) */
