/* Generated By:JavaCC: Do not edit this line. DDLParserVisitor.java Version 5.0 */
package org.eclipse.persistence.tools.dbws.metadata.parser;

public interface DDLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=981b7737952734b2ada088b0202eaf82 (do not edit this line) */
