/* Generated By:JavaCC: Do not edit this line. DDLParserTreeConstants.java Version 5.0 */
package org.eclipse.persistence.tools.dbws.metadata.parser;

public interface DDLParserTreeConstants
{
  public int JJTPARSEPLSQLPACKAGE = 0;
  public int JJTPARSETOPLEVELPROCEDURE = 1;
  public int JJTPARSETOPLEVELFUNCTION = 2;
  public int JJTPARSETABLE = 3;
  public int JJTALTERDECLARATION = 4;
  public int JJTPARSETYPE = 5;
  public int JJTVOID = 6;
  public int JJTCOLUMNDECLARATION = 7;
  public int JJTCOLUMNTYPESPEC = 8;
  public int JJTVARIABLEDECLARATION = 9;
  public int JJTTYPESPEC = 10;
  public int JJTTYPEDECLARATION = 11;
  public int JJTRECORDDECLARATION = 12;
  public int JJTFIELDDECLARATION = 13;
  public int JJTSUBTYPEDECLARATION = 14;
  public int JJTPLSQLTABLEDECLARATION = 15;
  public int JJTPLSQLTABLEINDEXBYDECLARATION = 16;
  public int JJTVARRAYDECLARATION = 17;
  public int JJTREFCURSORDECLARATION = 18;
  public int JJTREFCURSORTYPESPEC = 19;
  public int JJTCURSORDECLARATION = 20;
  public int JJTPROCEDURESPEC = 21;
  public int JJTFUNCTIONSPEC = 22;
  public int JJTFUNCTIONRETURNSPEC = 23;
  public int JJTARGUMENT = 24;
  public int JJTARGUMENTDEFAULTASSIGNMENT = 25;


  public String[] jjtNodeName = {
    "parsePLSQLPackage",
    "parseTopLevelProcedure",
    "parseTopLevelFunction",
    "parseTable",
    "alterDeclaration",
    "parseType",
    "void",
    "columnDeclaration",
    "columnTypeSpec",
    "variableDeclaration",
    "typeSpec",
    "typeDeclaration",
    "recordDeclaration",
    "fieldDeclaration",
    "subtypeDeclaration",
    "plsqlTableDeclaration",
    "plsqlTableIndexByDeclaration",
    "varrayDeclaration",
    "refCursorDeclaration",
    "refCursorTypeSpec",
    "cursorDeclaration",
    "procedureSpec",
    "functionSpec",
    "functionReturnSpec",
    "argument",
    "argumentDefaultAssignment",
  };
}
/* JavaCC - OriginalChecksum=ffd36579050adc0b39df6caa67b15a7d (do not edit this line) */
