/* Generated By:JavaCC: Do not edit this line. DDLParserVisitor.java Version 5.0 */
package org.eclipse.persistence.tools.database.metadata.parser;

@SuppressWarnings("all")
public interface DDLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=19385339b8305c5def76422d9db646fc (do not edit this line) */
