/* Generated By:JavaCC: Do not edit this line. DDLParserVisitor.java Version 5.0 */
package org.eclipse.persistence.tools.database.metadata.parser;

@SuppressWarnings("all")
public interface DDLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=7c78b3aff29757010997bec434ea3ee2 (do not edit this line) */
