/* Generated By:JavaCC: Do not edit this line. DDLParserTreeConstants.java Version 5.0 */
package org.eclipse.persistence.tools.database.metadata.parser;

@SuppressWarnings("all")
public interface DDLParserTreeConstants
{
  public int JJTPARSEPLSQLPACKAGE = 0;
  public int JJTPARSETOPLEVELPROCEDURE = 1;
  public int JJTPARSETOPLEVELFUNCTION = 2;
  public int JJTPARSETABLE = 3;
  public int JJTALTERDECLARATION = 4;
  public int JJTPARSETYPE = 5;
  public int JJTVOID = 6;
  public int JJTCOLUMNTYPESPEC = 7;
  public int JJTVARIABLEDECLARATION = 8;
  public int JJTDATATYPE = 9;
  public int JJTTYPESPEC = 10;
  public int JJTFIELDDECLARATION = 11;
  public int JJTFUNCTIONRETURNSPEC = 12;
  public int JJTARGUMENT = 13;
  public int JJTARGUMENTDEFAULTASSIGNMENT = 14;


  public String[] jjtNodeName = {
    "parsePLSQLPackage",
    "parseTopLevelProcedure",
    "parseTopLevelFunction",
    "parseTable",
    "alterDeclaration",
    "parseType",
    "void",
    "columnTypeSpec",
    "variableDeclaration",
    "datatype",
    "typeSpec",
    "fieldDeclaration",
    "functionReturnSpec",
    "argument",
    "argumentDefaultAssignment",
  };
}
/* JavaCC - OriginalChecksum=044fe26f3d64d43408612e4b7ae73ae5 (do not edit this line) */
